[project]
name = 'Cellular-Automata-Evolution'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.cellular-automata-management]
path = 'contracts/cellular-automata-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.evolution-parameters]
path = 'contracts/evolution-parameters.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
